In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

sa = pd.DataFrame()

# Teknoloji Teması

In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/IRT/rakip-analizi'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Teknoloji"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
5         TGX  Teknoloji
6         TAR  Teknoloji
7         FJB  Teknoloji
8         IVY  Teknoloji
9         ZFB  Teknoloji
10        GBV  Teknoloji
11        YZC  Teknoloji
12        DVT  Teknoloji
13        MTV  Teknoloji
14        MTX  Teknoloji
15        MET  Teknoloji
16        ZMY  Teknoloji
17        IJZ  Teknoloji
18        BVV  Teknoloji
19        ITP  Teknoloji
20        IJP  Teknoloji
21        YHZ  Teknoloji
22        TTE  Teknoloji
23        AFT  Teknoloji
24        YAY  Teknoloji
25        DHJ  Teknoloji
26        ICZ  Teknoloji
27        TFF  Teknoloji
28        GUH  Teknoloji
29        OJT  Teknoloji
30        IUH  Teknoloji
31        PIL  Teknoloji
32        IJC  Teknoloji
33        IRT  Teknoloji
34        HOA  Teknoloji
35        DTZ  Teknoloji
36        RTG  Teknoloji
37        KIB  Teknoloji

# Banka Teması

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/TAU/rakip-analizi/bankacilik'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Bankacılık"
sa = pd.concat([sa, df])
sa

   Fund Codes        Tema
0         TBE   Teknoloji
1         RPM   Teknoloji
2         BTE   Teknoloji
3         DYN   Teknoloji
4         VCY   Teknoloji
5         TGX   Teknoloji
6         TAR   Teknoloji
7         FJB   Teknoloji
8         IVY   Teknoloji
9         ZFB   Teknoloji
10        GBV   Teknoloji
11        YZC   Teknoloji
12        DVT   Teknoloji
13        MTV   Teknoloji
14        MTX   Teknoloji
15        MET   Teknoloji
16        ZMY   Teknoloji
17        IJZ   Teknoloji
18        BVV   Teknoloji
19        ITP   Teknoloji
20        IJP   Teknoloji
21        YHZ   Teknoloji
22        TTE   Teknoloji
23        AFT   Teknoloji
24        YAY   Teknoloji
25        DHJ   Teknoloji
26        ICZ   Teknoloji
27        TFF   Teknoloji
28        GUH   Teknoloji
29        OJT   Teknoloji
30        IUH   Teknoloji
31        PIL   Teknoloji
32        IJC   Teknoloji
33        IRT   Teknoloji
34        HOA   Teknoloji
35        DTZ   Teknoloji
36        RTG   Teknoloji
37        KIB   Teknoloji
0         TI3  Bankacılık
1         TIP  Bankacılık
2         YCP  Bankacılık
3         BST  Bankacılık
4         ADP  Bankacılık
5         YZH  Bankacılık
6         TAU  Bankacılık
7         TBP  Bankacılık
8         YCH  Bankacılık
9         INH  Bankacılık
10        TNI  Bankacılık
11        PAI  Bankacılık
12        ABU  Bankacılık

# Yerli Hisse

In [4]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/TAU/rakip-analizi/yerli-hisse'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Yerli Hisse"
sa = pd.concat([sa, df])
sa

   Fund Codes         Tema
0         TBE    Teknoloji
1         RPM    Teknoloji
2         BTE    Teknoloji
3         DYN    Teknoloji
4         VCY    Teknoloji
..        ...          ...
89        HGM  Yerli Hisse
90        IHT  Yerli Hisse
91        NHY  Yerli Hisse
92        RHS  Yerli Hisse
93        THD  Yerli Hisse

[145 rows x 2 columns]

# Metaverse

In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/DVT/rakip-analizi/metaverse'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Metaverse"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
0         DVT  Metaverse
1         MTV  Metaverse
2         MTX  Metaverse
3         MET  Metaverse
4         ZMY  Metaverse

[150 rows x 2 columns]

# Dijital Tema

In [6]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/DVT/rakip-analizi/dijital-temali-fonlar'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Dijital"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
4         ZMY  Metaverse
0         IJB    Dijital
1         DVT    Dijital
2         MTV    Dijital
3         MTX    Dijital

[154 rows x 2 columns]

# Tematik

In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/DVT/rakip-analizi/tematik-fonlar'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Tematik"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
46        MTV    Tematik
47        MTX    Tematik
48        MET    Tematik
49        ZMY    Tematik
50        IJZ    Tematik

[205 rows x 2 columns]

# Gümüş

In [8]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/MJG/rakip-analizi'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Gümüş"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
3         GMC      Gümüş
4         MJG      Gümüş
5         GUM      Gümüş
6         DMG      Gümüş
7         GTZ      Gümüş

[213 rows x 2 columns]

# Altın

In [9]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/KZL/rakip-analizi'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Altın"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
34        TCA      Altın
35        OGD      Altın
36        RBA      Altın
37        PKF      Altın
38        RJG      Altın

[252 rows x 2 columns]

# Endeks

In [10]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/TAU/rakip-analizi/endeks-temali-fonlar'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Tematik"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
22        ZJL    Tematik
23        DTL    Tematik
24        BID    Tematik
25        YHB    Tematik
26        APJ    Tematik

[279 rows x 2 columns]

# Sağlık

In [11]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/RPM/rakip-analizi'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Sağlık"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
0         TBE     Sağlık
1         RPM     Sağlık
2         IKL     Sağlık
3         AFS     Sağlık
4         GZG     Sağlık

[284 rows x 2 columns]

# Yabancı Hisse

In [12]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/AFS/rakip-analizi/yabanci-hisse'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Yabancı Hisse"
sa = pd.concat([sa, df])
sa

   Fund Codes           Tema
0         TBE      Teknoloji
1         RPM      Teknoloji
2         BTE      Teknoloji
3         DYN      Teknoloji
4         VCY      Teknoloji
..        ...            ...
3         GBG  Yabancı Hisse
4         AFA  Yabancı Hisse
5         TMG  Yabancı Hisse
6         ZSF  Yabancı Hisse
7         AOY  Yabancı Hisse

[292 rows x 2 columns]

# Yabancı Fon

In [13]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/AFS/rakip-analizi/yabanci-fonlar'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Yabancı Fonlar"
sa = pd.concat([sa, df])
sa

   Fund Codes            Tema
0         TBE       Teknoloji
1         RPM       Teknoloji
2         BTE       Teknoloji
3         DYN       Teknoloji
4         VCY       Teknoloji
..        ...             ...
15        GBC  Yabancı Fonlar
16        YTD  Yabancı Fonlar
17        TLE  Yabancı Fonlar
18        ARE  Yabancı Fonlar
19        TDG  Yabancı Fonlar

[312 rows x 2 columns]

# Oyun

In [14]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/BTE/rakip-analizi/oyun-sektoru'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Oyun"
sa = pd.concat([sa, df])
sa

   Fund Codes            Tema
0         TBE       Teknoloji
1         RPM       Teknoloji
2         BTE       Teknoloji
3         DYN       Teknoloji
4         VCY       Teknoloji
..        ...             ...
17        TLE  Yabancı Fonlar
18        ARE  Yabancı Fonlar
19        TDG  Yabancı Fonlar
0         BTE            Oyun
1         IJB            Oyun

[314 rows x 2 columns]

# Elektrikli Araç

In [15]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/YLO/rakip-analizi/elektrikli-arac'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Elektrikli Araç"
sa = pd.concat([sa, df])
sa

   Fund Codes             Tema
0         TBE        Teknoloji
1         RPM        Teknoloji
2         BTE        Teknoloji
3         DYN        Teknoloji
4         VCY        Teknoloji
..        ...              ...
0         DYN  Elektrikli Araç
1         VCY  Elektrikli Araç
2         IPJ  Elektrikli Araç
3         GVA  Elektrikli Araç
4         YLO  Elektrikli Araç

[319 rows x 2 columns]

# Gıda

In [16]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/MTS/rakip-analizi/tarim-gida'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Gıda"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
3         IJT       Gıda
4         YLC       Gıda
5         DFC       Gıda
6         GZL       Gıda
7         YTV       Gıda

[327 rows x 2 columns]

# Kıymetli Maden

In [17]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/OTJ/rakip-analizi/kiymetli-maden'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Kıymetli Maden"
sa = pd.concat([sa, df])
sa

   Fund Codes            Tema
0         TBE       Teknoloji
1         RPM       Teknoloji
2         BTE       Teknoloji
3         DYN       Teknoloji
4         VCY       Teknoloji
..        ...             ...
5         DFC            Gıda
6         GZL            Gıda
7         YTV            Gıda
0         KUT  Kıymetli Maden
1         OTJ  Kıymetli Maden

[329 rows x 2 columns]

# Emtia

In [18]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/GBZ/rakip-analizi/emtia-fonlari'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Emtia"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
4         KIF      Emtia
5         TGE      Emtia
6         ZCN      Emtia
7         OVD      Emtia
8         GBZ      Emtia

[338 rows x 2 columns]

# Eurobond

In [19]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/FUB/rakip-analizi/eurobond-borclanma-araclari'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Eurobond"
sa = pd.concat([sa, df])
sa

   Fund Codes       Tema
0         TBE  Teknoloji
1         RPM  Teknoloji
2         BTE  Teknoloji
3         DYN  Teknoloji
4         VCY  Teknoloji
..        ...        ...
4         AKE   Eurobond
5         IPV   Eurobond
6         FUB   Eurobond
7         TPL   Eurobond
8         GPA   Eurobond

[347 rows x 2 columns]

# Sürdürülebilirlik

In [20]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()

# Open the website
website_url = 'https://fintables.com/fonlar/MTS/rakip-analizi/surdurulebilirlik'
driver.get(website_url)

# Wait for the page to load (you may need to adjust the sleep time accordingly)
import time
time.sleep(5)

# Get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Extract fund codes from the HTML
fund_codes = []
fund_elements = soup.select('tr.cursor-pointer a[href^="/fonlar/"]')
for fund_element in fund_elements:
    fund_code = fund_element['href'].split('/')[-1]
    fund_codes.append(fund_code)

# Create a DataFrame
df = pd.DataFrame({'Fund Codes': fund_codes})

# Save the DataFrame to a CSV file


df["Tema"] = "Sürdürülebilirlik"
sa = pd.concat([sa, df])
sa

   Fund Codes               Tema
0         TBE          Teknoloji
1         RPM          Teknoloji
2         BTE          Teknoloji
3         DYN          Teknoloji
4         VCY          Teknoloji
..        ...                ...
9         IUT  Sürdürülebilirlik
10        DHM  Sürdürülebilirlik
11        GZV  Sürdürülebilirlik
12        ZSG  Sürdürülebilirlik
13        TJF  Sürdürülebilirlik

[361 rows x 2 columns]

In [21]:
sa.reset_index(inplace=True, drop=True)

sa

    Fund Codes               Tema
0          TBE          Teknoloji
1          RPM          Teknoloji
2          BTE          Teknoloji
3          DYN          Teknoloji
4          VCY          Teknoloji
..         ...                ...
356        IUT  Sürdürülebilirlik
357        DHM  Sürdürülebilirlik
358        GZV  Sürdürülebilirlik
359        ZSG  Sürdürülebilirlik
360        TJF  Sürdürülebilirlik

[361 rows x 2 columns]

In [22]:
def join_themes(themes):
    return ', '.join(set(themes))

# Group by 'Codes' and aggregate 'Tema' using the custom function
sa = sa.groupby('Fund Codes')['Tema'].agg(join_themes).reset_index()

sa

    Fund Codes                              Tema
0          AAV                       Yerli Hisse
1          ABU                        Bankacılık
2          ACC                       Yerli Hisse
3          ACK                       Yerli Hisse
4          ADP  Tematik, Yerli Hisse, Bankacılık
..         ...                               ...
240        ZLH              Tematik, Yerli Hisse
241        ZMY     Tematik, Teknoloji, Metaverse
242        ZPE                       Yerli Hisse
243        ZSF     Yabancı Fonlar, Yabancı Hisse
244        ZSG        Tematik, Sürdürülebilirlik

[245 rows x 2 columns]

In [23]:
sa.loc[sa["Tema"].str.contains("Teknoloji")]
sa.to_csv("fon_temalari.csv", index=False)